### ISSUE TITLE
Add Support for NOINDEX,NOFOLLOW

### ISSUE THREAD

**Issue by sprankhub** [elgentos/magento2-filtered-product-list-noindex#4]
From time to time, I get the requirement that the robots value should be `NOINDEX,NOFOLLOW` instead of `NOINDEX,FOLLOW`. What do you think about a respective configuration value under Stores > Configuration > Catalog > Catalog > Search Engine Optimization?

**Comment by peterjaap** [comment]
Fine by me, @ArjenMiedema ?

**Comment by ArjenMiedema** [comment]
I can agree on that. Shouldn't be too hard to implement. Are you planning on creating a PR for this, @sprankhub?
